### ISSUE TITLE
Add Warsh Mushaf

### ISSUE THREAD

**Issue by elhadjx** [islamic-network/api.alquran.cloud#83] opened 2024-08-20 06:26 UTC
and Please do not use the [qurancomplex](https://qurancomplex.gov.sa/) version because it's not right.

**Comment by meezaan** [comment] 2024-08-21 04:36
Duplicate of https://github.com/islamic-network/alquran-tools/issues/13#issuecomment-2299340321

**Closed by meezaan** 2024-08-21 04:36 UTC
