### ISSUE TITLE
Request to remove bismi from the first aya 

### ISSUE THREAD

**Issue by rashnk** [islamic-network/api.alquran.cloud#41] opened 2020-07-01 17:13 UTC
I dont think there is a need of bismilla in the first aya of surath, in the site(https://alquran.cloud/surah/94) itself bismi is seperately shown at the top of each sura. but the API adds bismi with the first aya,  refer the screenshot from the quran.cloud site

![image](https://user-images.githubusercontent.com/12730428/86272243-dd232c80-bbeb-11ea-813e-58e56e73b9b7.png)

Request to please remove bismi from the first Aya

Jazakallah khairan

**Comment by rashnk** [comment] 2020-07-01 17:14
This is API result , bismi added with the first aya

![image](https://user-images.githubusercontent.com/12730428/86272588-6dfa0800-bbec-11ea-9fce-05b05d3958db.png)

**Comment by papasmile** [comment] 2020-07-02 14:50
Asslaam alaykum wa rahmatullah,

Your request seems to be a duplicate of https://github.com/islamic-network/api.alquran.cloud/issues/17

**Comment by vipafattal** [comment] 2020-07-02 18:45
> Asslaam alaykum wa rahmatullah,
> 
> Your request seems to be a duplicate of #17

Yes, it's duplicated and it's already in the todo list for the API see [this](https://github.com/orgs/islamic-network/projects/5#card-41163946)

**Comment by meezaan** [comment] 2020-07-03 12:22
Closed as it is a duplicate.

**Closed by meezaan** 2020-07-03 12:22 UTC
